version: '3.9'

services:
  web:
    image: ghcr.io/inputstudio/hello-world:latest
    env_file:
      - stack.env # This file contains all the environment variables set in the stack editor
    # You can customize the compose file as you wish
    # ports:
    #   - 80:80
    # Have a look at the docs for more information: https://docs.docker.com/compose/compose-file/compose-file-v3/
      
    