name: Deploy

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          # TODO: Set your image name
          images: ghcr.io/inputstudio/hello-world
          tags: |
            type=sha
            type=raw,value=latest
            type=ref,event=branch

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    # Only deploy on push to main branch. Remove the following line if you want to deploy on every push.
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Trigger Portainer stack webhook
        run: |
          response=$(curl -X POST -w "%{http_code}" -o /dev/null -s ${{ secrets.PORTAINER_STACK_WEBHOOK }})
          if [ "$response" -ne 204 ]; then
            echo "Error: POST request failed with status code $response"
            exit 1
          fi
